FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/Gateway/ApiGateway/ApiGateway.csproj
RUN dotnet publish src/Gateway/ApiGateway/ApiGateway.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
COPY src/Gateway/ApiGateway/ocelot.json .
COPY src/Gateway/ApiGateway/ocelot.auth.json .
COPY src/Gateway/ApiGateway/ocelot.noauth.json .
EXPOSE 8080
ENTRYPOINT ["dotnet", "ApiGateway.dll"]