FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .
RUN ls -R src
RUN dotnet restore src/Services/UserService/UserService.API/UserService.API.csproj
RUN dotnet publish src/Services/UserService/UserService.API/UserService.API.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev
WORKDIR /src
COPY . .
RUN dotnet restore src/Services/UserService/UserService.API/UserService.API.csproj

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "UserService.API.dll"]
