FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY src/Services/AIAssistantService/python_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/Services/AIAssistantService/python_api/ .

# Ensure data directory with PDFs is copied
COPY src/Services/AIAssistantService/python_api/data/ ./data/
# copy src/Services/AIAssistantService/faiss_index ./faiss_index

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/src
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
