FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

COPY src/Services/VirtualPatientService/vp_api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY src/Services/VirtualPatientService/vp_api/ .

ENV PYTHONUNBUFFERED=1

EXPOSE 8080
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]